### PR TITLE
Adjustments for jakarta ee 10

### PR DESCRIPTION
**Pull request by asbachb**
see https://github.com/apache/netbeans/issues/5472

### CODE REVIEW

**Review by juneau001 — APPROVED** [review]
These changes look good...thanks!

**Comment by asbachb** [comment]
@juneau001 thanks for merging.

Do you need to do anything in addition so that the artifact is pushed to central?

**Comment by juneau001** [comment]
I will need to re-publish the updated archetype before it will be pushed to central.  I'll try to do it today.  Thanks

**Comment by asbachb** [comment]
I guess we might need to revert the change: https://github.com/jakartaee/persistence/issues/372

**Comment by juneau001** [comment]
Both versions of the archetype are now available on Maven Central.  Those being 1.0.0 and 1.0.1.  io.github.juneau001 » webapp-jakartaee10mvnrepository.com﻿
I guess we might need to revert the change: jakartaee/persistence#372

**Pull request merged**
